services:
  api:
    image: mobiledevelopment-api
    build:
      context: ./API
      dockerfile: MobileDevelopment.API/Dockerfile
    ports:
      - "8080:8080"
      - "8085:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__MsSqlDb=Server=db;Database=MobileDevelopmentDb;User Id=sa;Password=Your_password123;TrustServerCertificate=True;MultipleActiveResultSets=true
      - Jwt__SecretKey=CHANGE-ME-TO-A-SECURE-KEY-AT-LEAST-32-CHARS-LONG!!
      - Jwt__Issuer=FitTrackerAPI
      - Jwt__Audience=FitTrackerMobileClient
      - Jwt__AccessTokenExpirationMinutes=10
      - Jwt__RefreshTokenExpirationDays=7
      - ConnectionStrings__Redis=redis:6379
    depends_on:
      - db
      - redis

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Your_password123
      - MSSQL_MEMORY_LIMIT_MB=2048
    ports:
      - "1434:1433"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
