import { StyleSheet } from 'react-native';
import { Colors, Spacing } from '../theme/theme';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.background },
  header: { paddingHorizontal: Spacing.lg, paddingTop: Spacing.lg, paddingBottom: Spacing.md },
  headerTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 4 },
  title: { fontSize: 28, fontWeight: 'bold', color: Colors.foreground },
  editButton: { flexDirection: 'row', alignItems: 'center', backgroundColor: Colors.secondary, paddingHorizontal: 12, paddingVertical: 6, borderRadius: 8, borderWidth: 1, borderColor: Colors.border },
  editButtonText: { fontSize: 14, fontWeight: '500', marginLeft: 6, color: Colors.foreground },
  subtitle: { fontSize: 14, color: Colors.mutedForeground, marginBottom: Spacing.lg, textTransform: 'capitalize' },
  calendarRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: Spacing.md, paddingHorizontal: Spacing.lg },
  navButton: { width: 32, height: 32, borderRadius: 16, backgroundColor: Colors.secondary, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: Colors.border },
  daysRow: { flexDirection: 'row', flex: 1, justifyContent: 'space-between', paddingHorizontal: Spacing.xs },
  dayItem: { width: 44, height: 56, borderRadius: 16, alignItems: 'center', justifyContent: 'center', backgroundColor: Colors.secondary, borderWidth: 1, borderColor: Colors.border },
  dayActive: { backgroundColor: Colors.primary, borderColor: Colors.primary },
  dayName: { fontSize: 10, fontWeight: '500', color: Colors.mutedForeground, marginBottom: 4 },
  dayNameActive: { color: 'rgba(255,255,255,0.8)' },
  dayNumber: { fontSize: 14, fontWeight: 'bold', color: Colors.foreground },
  dayNumberActive: { color: '#fff' },
  content: { flex: 1, paddingHorizontal: Spacing.lg },
  scrollContent: { paddingBottom: Spacing.xl },
  selectedDayCard: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', borderRadius: 16, borderWidth: 1, padding: Spacing.md, marginBottom: Spacing.md },
  selectedDayLabel: { fontSize: 12, fontWeight: '600', textTransform: 'uppercase', letterSpacing: 0.4, marginBottom: 4 },
  selectedDayTitle: { fontSize: 17, fontWeight: '700', textTransform: 'capitalize' },
  selectedDayMeals: { fontSize: 13, fontWeight: '600' },
  dayChangeButton: { width: 28, height: 28, borderRadius: 14, alignItems: 'center', justifyContent: 'center' },
  addDayInlineButton: { flexDirection: 'row', alignItems: 'center', marginTop: 6 },
  addDayInlineText: { color: '#2563eb', fontSize: 12, fontWeight: '700', marginLeft: 2 },
  statsRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: Spacing.lg },
  statBox: { flex: 1, padding: Spacing.md, borderRadius: 16, marginHorizontal: Spacing.xs },
  statBoxPrimary: { backgroundColor: '#2563eb' },
  statBoxSecondary: { backgroundColor: Colors.secondary, borderWidth: 1, borderColor: Colors.border },
  statHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: Spacing.sm },
  statLabelPrimary: { fontSize: 14, color: 'rgba(255,255,255,0.9)', marginLeft: 6 },
  statLabelSecondary: { fontSize: 14, color: Colors.mutedForeground, marginLeft: 6 },
  statValuePrimary: { fontSize: 32, fontWeight: 'bold', color: '#fff' },
  statValueSecondary: { fontSize: 32, fontWeight: 'bold', color: Colors.foreground },
  statUnitPrimary: { fontSize: 12, color: 'rgba(255,255,255,0.75)', marginTop: 4 },
  statUnitSecondary: { fontSize: 12, color: Colors.mutedForeground, marginTop: 4 },
  macroSummaryCard: { flexDirection: 'row', justifyContent: 'space-between', borderRadius: 16, borderWidth: 1, padding: Spacing.md, marginBottom: Spacing.lg },
  macroItem: { flex: 1, alignItems: 'center' },
  macroLabel: { fontSize: 12, marginBottom: 4 },
  macroValue: { fontSize: 14, fontWeight: '700' },
  comparisonCard: { borderRadius: 16, borderWidth: 1, padding: Spacing.md, marginBottom: Spacing.lg },
  comparisonTitle: { fontSize: 16, fontWeight: '700', marginBottom: Spacing.sm },
  comparisonRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: Spacing.sm },
  comparisonLabel: { fontSize: 13, fontWeight: '600' },
  statusBadge: { paddingHorizontal: 10, paddingVertical: 5, borderRadius: 999 },
  status_ok: { backgroundColor: '#16a34a' },
  status_under: { backgroundColor: '#f59e0b' },
  status_over: { backgroundColor: '#ef4444' },
  status_neutral: { backgroundColor: '#64748b' },
  statusText: { color: '#fff', fontSize: 12, fontWeight: '700' },
  sectionHeaderRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: Spacing.md },
  sectionTitle: { fontSize: 18, fontWeight: '600', color: Colors.foreground },
  sectionActions: { flexDirection: 'row', alignItems: 'center' },
  actionButton: { width: 40, height: 40, borderRadius: 12, alignItems: 'center', justifyContent: 'center', marginLeft: Spacing.sm },
  actionButtonAdd: { backgroundColor: '#3b82f6' },
  mealsList: { gap: Spacing.sm },
  mealCard: { backgroundColor: Colors.secondary, padding: Spacing.md, borderRadius: 16, flexDirection: 'row', alignItems: 'center', borderWidth: 1, borderColor: Colors.border },
  mealIconWrapper: { width: 40, height: 40, borderRadius: 20, backgroundColor: '#eff6ff', alignItems: 'center', justifyContent: 'center', marginRight: Spacing.md },
  mealInfo: { flex: 1 },
  mealName: { fontSize: 14, fontWeight: '500', color: Colors.foreground, marginBottom: 2 },
  mealDesc: { fontSize: 12, color: Colors.mutedForeground },
  mealCalories: { fontSize: 14, fontWeight: '600', color: Colors.foreground },
  centerContainer: { flex: 1, justifyContent: 'center', alignItems: 'center', padding: Spacing.xl },
  emptyText: { fontSize: 16, color: Colors.mutedForeground, marginBottom: Spacing.lg },
  primaryButton: { backgroundColor: Colors.primary, paddingHorizontal: Spacing.lg, paddingVertical: Spacing.md, borderRadius: 12 },
  primaryButtonText: { color: '#fff', fontSize: 16, fontWeight: '600' },
  modalOverlay: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(0,0,0,0.45)' },
  modalDismiss: { flex: 1 },
  modalSheet: { borderTopLeftRadius: 24, borderTopRightRadius: 24, padding: Spacing.lg },
  modalTitle: { fontSize: 20, fontWeight: '800', marginBottom: Spacing.lg },
  inputLabel: { fontSize: 12, fontWeight: '700', marginBottom: 6, textTransform: 'uppercase', letterSpacing: 0.4 },
  modalInput: { minHeight: 48, borderRadius: 12, borderWidth: 1, paddingHorizontal: Spacing.md, marginBottom: Spacing.md },
  modalTextArea: { minHeight: 84, paddingTop: Spacing.sm, textAlignVertical: 'top' },
  modalGrid: { flexDirection: 'row', gap: Spacing.sm },
  modalGridItem: { flex: 1 },
  modalPrimaryButton: { height: 52, borderRadius: 14, backgroundColor: '#2563eb', alignItems: 'center', justifyContent: 'center', marginTop: Spacing.sm },
  modalPrimaryText: { color: '#fff', fontSize: 16, fontWeight: '800' },
});
