import { StyleSheet } from 'react-native';
import { Colors, Spacing } from '../theme/theme';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.background },
  header: { paddingHorizontal: Spacing.lg, paddingTop: Spacing.lg, paddingBottom: Spacing.md },
  headerTitleRow: { flexDirection: 'row', alignItems: 'flex-start', gap: Spacing.md },
  headerIcon: { width: 40, height: 40, borderRadius: 12, alignItems: 'center', justifyContent: 'center', marginTop: 2 },
  headerText: { flex: 1 },
  title: { fontSize: 28, fontWeight: 'bold' },
  subtitle: { fontSize: 14, marginTop: 8, lineHeight: 20 },
  content: { flex: 1, paddingHorizontal: Spacing.lg },
  scrollContent: { paddingBottom: Spacing.xl },
  calcCard: { flexDirection: 'row', borderRadius: 16, overflow: 'hidden', marginBottom: Spacing.md, borderWidth: 1, alignItems: 'center' },
  calcImage: { width: 96, height: 104 },
  calcInfo: { flex: 1, padding: Spacing.md },
  cardTitleRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 6 },
  cardIcon: { width: 30, height: 30, borderRadius: 10, alignItems: 'center', justifyContent: 'center', marginRight: Spacing.sm },
  calcName: { flex: 1, fontSize: 16, fontWeight: '600' },
  calcDesc: { fontSize: 12, lineHeight: 18 },
  chevron: { marginRight: Spacing.md },
  formCard: { borderRadius: 20, borderWidth: 1, padding: Spacing.lg, marginBottom: Spacing.md },
  inputGroup: { marginBottom: Spacing.md },
  inputLabel: { fontSize: 14, fontWeight: '600', marginBottom: 8 },
  segmentedControl: { flexDirection: 'row', borderWidth: 1, borderRadius: 14, padding: 4 },
  segmentButton: { flex: 1, height: 40, borderRadius: 10, alignItems: 'center', justifyContent: 'center' },
  segmentText: { fontSize: 14, fontWeight: '600' },
  activityGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: Spacing.sm },
  activityChip: { width: '48%', borderRadius: 14, borderWidth: 1, padding: Spacing.sm },
  activityText: { fontSize: 13, fontWeight: '600' },
  activityValue: { fontSize: 12, marginTop: 2 },
  primaryButton: { minHeight: 52, marginTop: Spacing.sm },
  resultBox: { padding: Spacing.xl, borderRadius: 20, marginBottom: Spacing.md },
  resultLabel: { color: 'rgba(255,255,255,0.85)', fontSize: 14, marginBottom: 8 },
  resultValue: { fontSize: 42, fontWeight: 'bold', color: '#ffffff' },
  resultRows: { marginTop: Spacing.lg, gap: Spacing.sm },
  resultRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  resultRowLabel: { color: 'rgba(255,255,255,0.8)', fontSize: 13 },
  resultRowValue: { color: '#ffffff', fontSize: 14, fontWeight: '700' },
  infoBox: { flexDirection: 'row', alignItems: 'flex-start', gap: Spacing.sm, borderWidth: 1, borderRadius: 14, padding: Spacing.md },
  infoText: { flex: 1, fontSize: 13, lineHeight: 19 },
});
