import { StyleSheet } from 'react-native';
import { Spacing } from '../theme/theme';

export const styles = StyleSheet.create({
  container: { flex: 1 },
  centered: { justifyContent: 'center', alignItems: 'center', padding: Spacing.xl },
  errorText: { marginTop: Spacing.md, fontSize: 14, textAlign: 'center' },
  retryBtn: { marginTop: Spacing.lg, paddingHorizontal: Spacing.lg, paddingVertical: Spacing.sm, backgroundColor: '#3b82f6', borderRadius: 12 },
  retryText: { color: '#fff', fontWeight: '500' },
  header: { paddingHorizontal: Spacing.lg, paddingBottom: Spacing.md },
  titleRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' },
  title: { fontSize: 26, fontWeight: 'bold', marginBottom: 4 },
  subtitle: { fontSize: 14 },
  editBtn: { width: 40, height: 40, borderRadius: 12, alignItems: 'center', justifyContent: 'center', borderWidth: 1, marginLeft: Spacing.md },
  content: { flex: 1, paddingHorizontal: Spacing.lg },
  scrollContent: { paddingTop: Spacing.sm },
  statsGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: Spacing.sm, marginBottom: Spacing.lg },
  statBox: { width: '47.5%', padding: Spacing.md, borderRadius: 16, borderWidth: 1 },
  statHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 8 },
  statLabel: { fontSize: 13, marginLeft: 6 },
  statValue: { fontSize: 22, fontWeight: 'bold' },
  sectionRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: Spacing.md },
  sectionTitle: { fontSize: 18, fontWeight: '600' },
  addBtn: { flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: '#3b82f6', paddingHorizontal: 14, paddingVertical: 8, borderRadius: 10 },
  addBtnText: { color: '#fff', fontWeight: '600', fontSize: 14 },
  emptyExercises: { alignItems: 'center', padding: Spacing.xl, borderRadius: 16, borderWidth: 1.5, borderStyle: 'dashed', marginBottom: Spacing.lg },
  emptyExTitle: { fontSize: 18, fontWeight: '600', marginTop: Spacing.md },
  emptyExDesc: { fontSize: 14, marginTop: 4 },
  exerciseCard: { borderRadius: 16, padding: Spacing.md, borderWidth: 1, marginBottom: Spacing.sm },
  exerciseHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: Spacing.sm },
  exerciseName: { fontSize: 16, fontWeight: '600', flex: 1 },
  addSetBtn: { flexDirection: 'row', alignItems: 'center', gap: 4, paddingHorizontal: 10, paddingVertical: 5, borderRadius: 8, borderWidth: 1, borderColor: '#3b82f6' },
  addSetBtnText: { fontSize: 12, color: '#3b82f6', fontWeight: '600' },
  setsHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 4 },
  setHeaderText: { fontSize: 12 },
  setCol: { flex: 1, fontSize: 14, fontWeight: '500' },
  setRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: 8, borderTopWidth: 1 },
  deleteSet: { width: 32, alignItems: 'center' },
  notesBox: { borderRadius: 16, padding: Spacing.md, borderWidth: 1, marginTop: Spacing.sm },
  notesTitle: { fontSize: 16, fontWeight: '600', marginBottom: 6 },
  notesText: { fontSize: 14, lineHeight: 22 },
  modalOverlay: { flex: 1, justifyContent: 'flex-end' },
  modalDismiss: { flex: 1, backgroundColor: 'rgba(0,0,0,0.4)' },
  modalSheet: { borderTopLeftRadius: 24, borderTopRightRadius: 24, padding: Spacing.lg, paddingTop: Spacing.md },
  modalHandle: { width: 40, height: 4, borderRadius: 2, backgroundColor: '#94a3b8', alignSelf: 'center', marginBottom: Spacing.lg },
  modalTitle: { fontSize: 20, fontWeight: 'bold', marginBottom: 4 },
  modalSubtitle: { fontSize: 14, marginBottom: Spacing.lg },
  modalFields: { flexDirection: 'row', gap: Spacing.sm, marginBottom: Spacing.lg },
  modalField: { flex: 1 },
  modalLabel: { fontSize: 12, fontWeight: '500', marginBottom: 6 },
  modalInput: { borderWidth: 1, borderRadius: 12, paddingHorizontal: 12, height: 48, fontSize: 16 },
  modalSaveBtn: { backgroundColor: '#3b82f6', height: 52, borderRadius: 14, alignItems: 'center', justifyContent: 'center' },
  modalSaveBtnText: { color: '#fff', fontSize: 16, fontWeight: '600' },
});
